version: '3.8'

services:
  quasar-app:
    image: quasar-dev-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - .:/app
      - /app/node_modules
    command: quasar dev --hostname 0.0.0.0
